basel:
  name: Covid19-Scenarios (Neher)
  origin: Neher Lab - Biozentrum Basel
  enabled: true
  imageURL: ghcr.io/covid-policy-modelling/basel-connector/basel-connector:latest
  metaURLs:
    code: https://github.com/neherlab/covid19_scenarios
    website: https://covid19-scenarios.org/about
  description: |
    We implement an age-stratified SEIR model with additional categories
    for individuals exposed to the virus that are not yet infectious, severely sick
    people in need of hospitalization, people in critical condition, and a fatal category.
    The model is currently under active development and the US state level parameters are under review.
  supportedParameters:
    - contactReduction
    - r0
  supportedRegions:
    AD:
    AE:
    AF:
    AG:
    AL:
    AM:
    AR:
    AT:
    AU:
    AZ:
    BA:
    BB:
    BD:
    BE:
    BF:
    BG:
    BH:
    BI:
    BJ:
    BN:
    BO:
    BR:
    BS:
    BT:
    BW:
    BY:
    BZ:
    CA:
      - CA
      - CA-AB
      - CA-BC
      - CA-MB
      - CA-NB
      - CA-NL
      - CA-NS
      - CA-NT
      - CA-NU
      - CA-ON
      - CA-PE
      - CA-QC
      - CA-SK
      - CA-YT
    CF:
    CH:
      - CH
      - CH-AG
      - CH-AI
      - CH-AR
      - CH-BE
      - CH-BL
      - CH-BS
      - CH-FR
      - CH-GE
      - CH-GL
      - CH-GR
      - CH-JU
      - CH-LU
      - CH-NE
      - CH-NW
      - CH-OW
      - CH-SG
      - CH-SH
      - CH-SO
      - CH-SZ
      - CH-TG
      - CH-TI
      - CH-UR
      - CH-VD
      - CH-VS
      - CH-ZG
      - CH-ZH
    CL:
    CM:
    CN:
    CO:
    CR:
    CU:
    CV:
    CY:
    CZ:
    DE:
      - DE
      - DE-BB
      - DE-BE
      - DE-BW
      - DE-BY
      - DE-HB
      - DE-HE
      - DE-HH
      - DE-MV
      - DE-NI
      - DE-NW
      - DE-RP
      - DE-SH
      - DE-SL
      - DE-SN
      - DE-ST
      - DE-TH
    DJ:
    DK:
    DM:
    DO:
    DZ:
    EC:
    EE:
    EG:
    ES:
      - ES
      - ES-AN
      - ES-AR
      - ES-AS
      - ES-CB
      - ES-CE
      - ES-CL
      - ES-CM
      - ES-CN
      - ES-CT
      - ES-EX
      - ES-GA
      - ES-IB
      - ES-MC
      - ES-MD
      - ES-ML
      - ES-NC
      - ES-PV
      - ES-RI
      - ES-VC
    ET:
    FI:
    FJ:
    FM:
    FO:
    FR:
      - FR
      - FR-ARA
      - FR-BFC
      - FR-BRE
      - FR-COR
      - FR-CVL
      - FR-GES
      - FR-GF
      - FR-GUA
      - FR-HDF
      - FR-IDF
      - FR-LRE
      - FR-MAY
      - FR-MQ
      - FR-NAQ
      - FR-NOR
      - FR-OCC
      - FR-PAC
      - FR-PDL
    GA:
    GB:
    GD:
    GE:
    GH:
    GI:
    GL:
    GM:
    GN:
    GQ:
    GR:
    GT:
    GW:
    GY:
    HK:
    HN:
    HR:
    HT:
    HU:
    ID:
    IE:
    IL:
    IN:
      - IN
      - IN-AN
      - IN-AP
      - IN-AR
      - IN-AS
      - IN-BR
      - IN-CH
      - IN-CT
      - IN-DD
      - IN-DL
      - IN-DN
      - IN-GA
      - IN-GJ
      - IN-HP
      - IN-HR
      - IN-JH
      - IN-JK
      - IN-KA
      - IN-KL
      - IN-LD
      - IN-MH
      - IN-ML
      - IN-MN
      - IN-MP
      - IN-MZ
      - IN-NL
      - IN-OR
      - IN-PB
      - IN-PY
      - IN-RJ
      - IN-SK
      - IN-TH
      - IN-TN
      - IN-TR
      - IN-UP
      - IN-UT
      - IN-WB
    IQ:
    IR:
    IS:
    IT:
      - IT
      - IT-21
      - IT-23
      - IT-25
      - IT-32
      - IT-34
      - IT-36
      - IT-42
      - IT-45
      - IT-52
      - IT-55
      - IT-57
      - IT-62
      - IT-65
      - IT-67
      - IT-72
      - IT-75
      - IT-77
      - IT-78
      - IT-82
      - IT-88
      - IT-BZ
      - IT-TN
    JM:
    JO:
    JP:
      - JP
      - JP-47
    KE:
    KG:
    KH:
    KI:
    KM:
    KN:
    KP:
    KR:
    KW:
    KZ:
    LA:
    LB:
    LC:
    LI:
    LK:
    LR:
    LT:
    LU:
    LV:
    LY:
    MA:
    MC:
    MD:
    ME:
    MG:
    MH:
    MK:
    ML:
    MM:
    MN:
    MT:
    MU:
    MV:
    MW:
    MX:
    MY:
    MZ:
    NA:
    NI:
    NL:
    NO:
    NP:
    NR:
    NZ:
    OM:
    PA:
    PE:
    PH:
      - PH
      - PH-00
      - PH-01
      - PH-02
      - PH-03
      - PH-05
      - PH-06
      - PH-07
      - PH-08
      - PH-09
      - PH-10
      - PH-11
      - PH-12
      - PH-13
      - PH-14
      - PH-15
      - PH-40
      - PH-41
    PK:
    PL:
    PT:
    PW:
    PY:
    QA:
    RO:
    RS:
    RU:
    SA:
    SB:
    SC:
    SD:
    SE:
      - SE
      - SE-AB
    SG:
    SI:
    SK:
    SM:
    SN:
    SO:
    SR:
    ST:
    SV:
    SY:
    SZ:
    TG:
    TH:
    TJ:
    TL:
    TM:
    TN:
    TO:
    TR:
    TT:
    TW:
    TZ:
    UA:
    UG:
    US:
      - US
      - US-AK
      - US-AL
      - US-AR
      - US-AZ
      - US-CA
      - US-CO
      - US-CT
      - US-DC
      - US-DE
      - US-FL
      - US-GA
      - US-HI
      - US-IA
      - US-ID
      - US-IL
      - US-IN
      - US-KS
      - US-KY
      - US-LA
      - US-MA
      - US-MD
      - US-ME
      - US-MI
      - US-MN
      - US-MO
      - US-MS
      - US-MT
      - US-NC
      - US-ND
      - US-NE
      - US-NH
      - US-NJ
      - US-NM
      - US-NV
      - US-NY
      - US-OH
      - US-OK
      - US-OR
      - US-PA
      - US-RI
      - US-SC
      - US-SD
      - US-TN
      - US-TX
      - US-UT
      - US-VA
      - US-VT
      - US-WA
      - US-WI
      - US-WV
      - US-WY
    UY:
    UZ:
    VC:
    VE:
    VN:
    YE:
    ZA:
    ZM:
    ZW:
