version: "3.7"
services:
  test:
    build:
      context: ../..
      dockerfile: ./packages/neherlab-covid-19-scenarios/Dockerfile
      target: test
      args:
        - BASEL_VERSION=${BASEL_VERSION}

  release:
    build:
      context: ../..
      dockerfile: ./packages/neherlab-covid-19-scenarios/Dockerfile
      target: release
      args:
        - BASEL_VERSION=${BASEL_VERSION}
    # This is set this way to make things easier in the Actions workflows.
    image: image

  run-model:
    build:
      context: ../..
      dockerfile: ./packages/neherlab-covid-19-scenarios/Dockerfile
      target: release
      args:
        - BASEL_VERSION=${BASEL_VERSION}
    volumes:
      - ./test/test-job.json:/data/input/inputFile.json:ro
      - ./output:/data/output:rw
      - ./log:/data/log:rw

  remote-image:
    image: ghcr.io/${GITHUB_REPO:-covid-policy-modelling/model-runner}/neherlab-covid-19-scenarios-connector:main
    tty: true
    volumes:
      - ./test/test-job.json:/data/input/inputFile.json:ro
      - ./output:/data/output:rw
      - ./log:/data/log:rw
