name: Basel Connector-Publish Docker Images for Tags/Releases
on:
  push:
    # Publish `neherlab-covid-19-scenarios/v1.2.3` tags as `neherlab-covid-19-scenarios-connector` releases.
    tags:
      - 'neherlab-covid-19-scenarios/v*'

env:
  PACKAGE_NAME: neherlab-covid-19-scenarios
  IMAGE_NAME: neherlab-covid-19-scenarios-connector

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/neherlab-covid-19-scenarios

    strategy:
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Login to GitHub Packages for base image
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ secrets.GPR_USER }}
          password: ${{ secrets.GPR_PAT }}

      - name: Build image
        run: docker-compose build release

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GPR_USER }}
          password: ${{ secrets.GPR_PAT }}

      - name: Push image (Local)
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/$PACKAGE_NAME"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Always tag with git sha or version tag
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
