name: Model Runner-Publish Docker Images for Tags/Releases
on:
  push:
    # Publish `model-runner/v1.2.3` tags as model-runner releases.
    tags:
      - 'model-runner/v*'

env:
  PACKAGE_NAME: model-runner
  IMAGE_NAME: model-runner

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/model-runner

    strategy:
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker-compose build release

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GPR_USER }}
          password: ${{ secrets.GPR_PAT }}

      - name: Push image (Local)
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/$PACKAGE_NAME"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Always tag with git sha or version tag
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
